version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_backend_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=systock
      - DB_USERNAME=usertest
      - DB_PASSWORD=secret
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: usertest
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: systock
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
